### ISSUE TITLE
What is an “org-mode compatible markdown table”?

### ISSUE THREAD

**Issue by p3k** [saulpw/visidata.org#30]
**Small description**

The docs state under SUPPORTED OUTPUT FORMATS:

>  md (org-mode compatible markdown table)

org-mode is related to emacs obv but the generated file does not contain a valid [markdown table syntax](
https://www.markdownguide.org/extended-syntax/#tables).

In fact, rendering the output with an extended Markdown parser [does not output a beautiful table](https://jbt.github.io/markdown-editor/#q0nLz69JSiyq4arR1dXVBmIgS8FQoUbBSKGGCwA=):

```md
|foo|bar|
|---+---|
| 1 | 2 |
```

|foo|bar|
|---+---|
| 1 | 2 |

**Expected result**

Either a correct Markdown table…

```md
|foo|bar|
|---|---|
| 1 | 2 |
```

|foo|bar|
|---|---|
| 1 | 2 |

…or a less misleading documentation – e.g. by preventing a reference to Markdown and just calling it org-mode table.

**Steps to reproduce with sample data and a .vd**

Sample data in file `test.tsv`:

```tsv
foo     bar
1       2

```

```plain
→ vd -b test.tsv -o test.md
opening test as tsv
saving to test.md as md
test.md save finished

→ python -m markdown -x tables test.md
<p>|foo                 |bar                 |
|--------------------+--------------------|
|1                   |2                   |</p>
```

**Additional context**

```plain
→ vd -v
saul.pw/VisiData v1.5.2
```

**Comment by anjakefala** [comment]
@p3k We are planning on updating the /formats page to have clearer info on what is available in which version of VisiData. Thanks so much for nudging us to do that!

For now, I removed "org-mode" from the /formats page, and left it just as "markdown table". I think the table format that is shipped with 1.5.2 is GitHub compatible. This is because I asked Saul to make me that loader originally so that I could make tables on GitHub. :joy:
